// Consent body text — THE single source, rendered two ways.
//
// The portal reads it through /api/gfc/intake and renders the cards; the PDF
// generator reads it directly and renders one signed document per consent. It
// lives here rather than as JSX in portal.html because the PDF generator is
// server-side and cannot read JSX, and a second copy of legal text is a copy
// that drifts. That is not hypothetical: the client document list kept its own
// copy of the consent TITLES and had already drifted to the old
// emergencyFinancial wording with no entry for ihpcServiceAgreement at all.
//
// Ported verbatim from docs/GFC_Consent_Source_Text_v2_1.md, which is the
// authority where this and it differ. Do not compose new legal language here.
// Packet mechanics ("Packet 1 of 2", "signed in one sitting", "take this packet
// away") are deliberately absent and test/consent_registry.test.js fails the
// build if they reappear; cross-references are by document NAME, never number.
//
// Block shape: ['title'|'h'|'p', text] or ['ul', [items]].
// `**` marks emphasis, so a renderer can bold without either side parsing HTML.
const CONSENT_TEXT = {
  serviceAgreement: [
    ["title", "Service Agreement"],
    ["p", "This agreement sets out the **non-medical** personal home care services Godwins Family Care LLC will provide, what they cost, and how either of us may change or end them. It is not an agreement for medical care. Please read it and ask about anything that is not clear before signing."],
    ["h", "1. Parties"],
    ["p", "Godwins Family Care LLC, a Georgia limited liability company licensed by the Georgia Department of Community Health, Healthcare Facility Regulation Division, as a Private Home Care Provider under license number **PHCP013073**, in effect as of the date of this agreement. Your details are recorded once on your Client Information Face Sheet."],
    ["h", "2. What Your Caregiver Will Do"],
    ["p", "**Track A2, Comprehensive Home Care.** Non-medical personal care and companion services delivered in your residence. This is the full scope of what a Godwins Family Care caregiver is trained and authorized to do for you. Your plan of care records which of these you have asked for."],
    ["p", "**Bathing and hygiene.** Bathing and showering, standby assistance while you bathe so you do not fall, bed and sponge bathing, washing and styling hair, shaving, skin care and lotion, nail filing and hand and foot care, oral care and denture care, perineal care."],
    ["p", "**Dressing and grooming.** Choosing clothing, dressing and undressing, fastening buttons and zippers, putting on and removing compression stockings, applying braces, splints, or a prosthesis, and help with glasses, hearing aids, and dentures."],
    ["p", "**Toileting and continence.** Getting to and from the toilet, bedside commode, bedpan and urinal, changing incontinence briefs and pads, cleaning and changing after an accident, and emptying an external urinary drainage bag where your plan of care includes it."],
    ["p", "**Mobility and transfers.** Walking assistance, gait belt use, help with a cane, walker, or wheelchair, transfers between bed, chair, toilet, and car, turning and repositioning to protect the skin, range of motion movement as instructed, and fall prevention throughout the home."],
    ["p", "**Eating and nutrition.** Planning and preparing meals and snacks, following a special diet, cutting food, feeding assistance, encouraging fluids, watching what you are actually eating and drinking, and cleaning up afterward."],
    ["p", "**Medication support — reminders only.** Reminding you when a dose is due, reading a label aloud, opening a container, bringing you your pre-filled pill organizer and a glass of water, picking up refills, and reporting a missed or doubled dose to Godwins Family Care the same day."],
    ["p", "**Home and housekeeping.** Light housekeeping, vacuuming, sweeping and mopping, dusting, cleaning the kitchen and bathroom, washing dishes, making the bed and changing linens, laundry and folding, taking out trash, tidying, and clearing trip hazards from walkways."],
    ["p", "**Errands and transportation.** Grocery shopping with you or for you, pharmacy pickup, post office and bank trips, driving you to appointments, staying with you at the appointment, and helping you in and out of the car."],
    ["p", "**Companionship.** Conversation, reading aloud, sorting and answering mail, games, hobbies, walks, attending church or community activities with you, setting up video calls with family, and gentle cues for the day, date, and routine."],
    ["p", "**Household support.** Feeding and letting out pets, watering plants, answering the door and phone as you direct, checking that smoke and carbon monoxide detectors are working, and reporting anything in the home that needs repair."],
    ["p", "**Observation and reporting.** A written note at every visit, and same-day reporting to Godwins Family Care of any change in your condition, mood, appetite, sleep, skin, mobility, or safety, and of any fall. Changes are escalated to you, your responsible party, and, where you have authorized it, your medical providers."],
    ["p", "**Supervision.** Care is delivered under the supervision of Godwins Family Care. A supervisory visit is conducted at the outset and at regular intervals thereafter, and your plan of care is reviewed and updated as your needs change."],
    ["p", "**What a caregiver does not do.** These services are non-medical. A caregiver does not administer or fill medication, give injections, test blood sugar or give insulin, perform wound or ostomy care, insert or change a catheter, manage tube feeding, take clinical measurements as a medical assessment, provide physical or occupational therapy, or make any clinical decision or diagnosis. A caregiver also does not perform heavy cleaning such as moving furniture, washing exterior windows, or yard work, does not lift alone beyond what is safe, does not care for other members of the household, and does not manage your money, accounts, or bill paying. If you need any of these, tell us and we will help you arrange it with a licensed clinician or the right provider under a separate agreement."],
    ["h", "3. Rates and Minimums"],
    ["p", "**Caregiver travel.** Travel between the caregiver's home and your residence is not billed to you and is not your responsibility."],
    ["p", "**Rate changes.** Godwins Family Care will give at least thirty days written notice before any rate change. You may end this agreement without penalty if a rate change is not acceptable."],
    ["h", "4. Schedule"],
    ["p", "The schedule is agreed at the start of service and may be adjusted in writing by mutual agreement. Service is scheduled in blocks of at least four hours on any day care is provided."],
    ["h", "5. Billing and Payment"],
    ["p", "**Invoicing.** Godwins Family Care invoices every two weeks for hours worked. Invoices are due within fourteen days of the invoice date."],
    ["p", "**Long term care insurance.** Where you hold a long term care insurance policy, Godwins Family Care will provide the documentation the carrier requires, including invoices, visit records, and caregiver time verification, and will assist with the claim. You remain responsible for payment of all invoices. Amounts the carrier declines, delays, or pays below the invoiced total remain your responsibility."],
    ["p", "**Late payment.** Accounts more than thirty days past due may result in suspension of service after written notice. Godwins Family Care will give reasonable notice and will not suspend care without first attempting to reach you and your responsible party."],
    ["h", "6. Scheduling, Cancellation, and Coverage"],
    ["p", "**Cancellation by the client.** Please give at least twenty four hours notice to cancel or change a scheduled visit. Visits cancelled with less than twenty four hours notice may be billed at the four hour daily minimum."],
    ["p", "**Coverage and continuity.** Godwins Family Care is responsible for staffing every scheduled visit. If the assigned caregiver is unavailable, Godwins Family Care will arrange a qualified substitute and notify you in advance whenever possible."],
    ["p", "**Caregiver matching.** You will meet a proposed caregiver before service begins and may decline the match at any time and request a different caregiver. Godwins Family Care will make reasonable efforts to maintain caregiver continuity."],
    ["p", "**Access to the home.** You agree to provide safe access to the residence and a safe working environment, including working smoke detectors, and to disclose any known hazard, firearm in the home, or animal that could affect caregiver safety."],
    ["h", "7. Our Caregivers"],
    ["p", "**Employment and screening.** All caregivers are W2 employees of Godwins Family Care, not independent contractors. Each completes a criminal background check including fingerprint-based screening, abuse registry screening, exclusion list screening, reference and work history verification, tuberculosis screening, drug screening, and orientation and competency validation before providing care."],
    ["p", "**Insurance.** Godwins Family Care carries general liability, professional liability, and workers compensation coverage on its caregivers. You are not the employer of the caregiver and have no payroll, tax, or workers compensation obligation."],
    ["p", "**Direct hiring.** You agree not to employ or engage, directly or through any other agency, any caregiver introduced by Godwins Family Care, during service and for twelve months after service ends. Recruiting, screening, training, and insuring caregivers is a substantial cost, and this provision protects that investment. If you wish to hire a caregiver directly, please raise it with Godwins Family Care and a release may be arranged."],
    ["p", "**Gifts, money, and property.** Caregivers may not accept gifts, loans, tips, or money from clients or families, may not be named in a client's will or given power of attorney, and may not use a client's vehicle, credit card, or accounts except as expressly authorized in writing for approved errands."],
    ["p", "**Concerns.** Any concern about a caregiver or the care provided should be reported to Godwins Family Care at 404-913-6705 or admin@godwinsfamilycarellc.com. Concerns are investigated promptly and you will receive a response."],
    ["h", "8. Term and Termination"],
    ["p", "This agreement begins on the start date of service and continues until ended by either party. You may end it at any time, for any reason, with fourteen days written notice, and are responsible for services provided through the end date."],
    ["p", "Godwins Family Care may end this agreement with fourteen days written notice, and may end service immediately, without the notice period, where a caregiver's safety is at risk, where care needs exceed what may lawfully be provided under a private home care provider license, or where the account is materially past due after written notice. Where Godwins Family Care ends service, it will provide reasonable assistance in identifying alternative care resources."],
    ["h", "9. General Terms"],
    ["p", "**Scope of the agreement, and what it is not.** This agreement covers non-medical private home care only. It is not an agreement for medical or clinical care and creates no provider-patient relationship."],
    ["p", "It does not include and does not obligate you to accept in-home primary care, nursing visits, medical treatment, prescribing, care coordination or chronic care management billed to Medicare or any other health plan, or any other clinical service. Each of those is a separate service under a separate written agreement with its own consents, and you are free to choose any provider for any of them. **Declining medical care from Godwins Family Care has no effect on the home care provided under this agreement, and accepting home care is never a condition of receiving medical care.**"],
    ["p", "**Records and privacy.** Godwins Family Care maintains a record of services provided. Your information is handled in accordance with the Notice of Privacy Practices provided with this agreement."],
    ["p", "**Governing law and entire agreement.** This agreement is governed by the laws of the State of Georgia. It is the entire agreement between the parties on this subject and replaces any prior understanding. Changes must be in writing and signed by both parties. If any provision is held unenforceable, the rest remains in effect."],
    ["p", "**Non-discrimination.** Godwins Family Care provides services without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, disability, or veteran status."],
  ],
  ihpcServiceAgreement: [
    ["title", "In-Home Primary Care Services Agreement"],
    ["p", "This agreement sets out the **medical** care Godwins Family Care will provide in your home, who provides it, and what it costs. It is separate from your home care agreement and does not replace it."],
    ["p", "**You are under no obligation to sign it.** Your home care does not change, pause, or cost more if you decline, and you are free to receive medical care from any provider you choose."],
    ["h", "1. Who Provides Your Care"],
    ["p", "Your care is delivered by a board-certified family nurse practitioner licensed in Georgia, working with a collaborating physician as Georgia law requires. You will be told the name and credentials of anyone who comes to your home before the visit."],
    ["h", "2. What In-Home Primary Care Includes"],
    ["p", "**Medical visits in your home.** History and physical examination, vital signs, review of your conditions, and a written assessment and plan at every visit. Visits are scheduled; you are not seen on demand."],
    ["p", "**Diagnosis and treatment.** Evaluating new symptoms, diagnosing acute and chronic conditions, ordering and interpreting laboratory work and imaging, and treating what can safely be treated at home."],
    ["p", "**Prescribing and medication management.** Writing and renewing prescriptions, reviewing everything you take for interactions and duplication, simplifying a complicated regimen, and coordinating with your pharmacy."],
    ["p", "**Chronic disease management.** Regular management of conditions such as high blood pressure, diabetes, heart failure, COPD, arthritis, and cognitive change, with a schedule of follow-up matched to how you are doing."],
    ["p", "**Preventive care.** Vaccinations, screening recommendations appropriate to your age and health, fall risk assessment, and advance care planning conversations if you want them."],
    ["p", "**Referrals and coordination.** Referrals to specialists, coordination with your cardiologist or other physicians, hospital follow-up after a discharge, and orders for home health, therapy, or equipment where you qualify."],
    ["p", "**What this service is not.** It is not emergency care and not a substitute for 911. It is not twenty four hour coverage; the practice keeps business hours with an on-call line after hours. It is not Medicare home health, which is a separate benefit requiring a separate order and agency. It is not personal care, bathing, housekeeping, or companionship, which is your home care service under a separate agreement. And it does not require you to keep home care with Godwins Family Care, or to use us at all."],
    ["h", "3. Visits, Scheduling, and After Hours"],
    ["p", "**Visit frequency.** Set with you based on your conditions and reviewed at each visit. Most patients are seen monthly to quarterly, with additional visits when something changes."],
    ["p", "**Between visits.** Call 404-913-6705 during business hours for questions, medication problems, or a new symptom. After hours the line reaches on-call. If the problem is urgent and you cannot reach us, call 911 or go to the emergency department. Do not wait for a return call."],
    ["p", "**Missed visits.** Please give twenty four hours notice if you need to reschedule. Repeated missed visits without notice may end this agreement."],
    ["h", "4. Cost"],
    ["p", "Visits are billed to Medicare or your health plan. What you owe depends on your coverage: a deductible that has not been met, a coinsurance or copay amount, and anything your plan does not cover. Your Assignment of Benefits and Financial Responsibility sets this out in full."],
    ["p", "You will be told in advance, in writing, before any service that your plan is not expected to cover. You are never billed for a service you were not warned about."],
    ["h", "5. Records and Communication"],
    ["p", "Your medical record is kept in the practice's electronic health record. You may request a copy at any time. How the practice uses and protects your information is described in the Medical Practice Notice of Privacy Practices, which is separate from the home care agency notice you already received."],
    ["h", "6. Ending This Agreement"],
    ["p", "You may end medical care at any time, for any reason, with no effect on your home care. Godwins Family Care may end this agreement with thirty days written notice, during which urgent needs are still covered, and will provide your records and reasonable help finding another provider."],
    ["p", "**Ending this agreement does not end your home care. Ending your home care does not end this agreement. They are independent.**"],
  ],
  financialAgreement: [
    ["title", "Financial Agreement"],
    ["p", "Rates, billing, and cancellation, stated plainly and on one page. This repeats the money terms from your Service Agreement so nothing about cost is buried."],
    ["h", "1. What You Pay"],
    ["p", "Your agreed rate and any minimums are recorded on your rate schedule and on your Client Information Face Sheet."],
    ["h", "2. How You Are Billed"],
    ["p", "**Invoices.** Every two weeks, for hours actually worked. Payment is due within fourteen days of the invoice date."],
    ["p", "**Cancellations.** Please give at least twenty four hours notice to cancel or change a visit. A visit cancelled with less notice may be billed at the four hour daily minimum."],
    ["p", "**Rate changes.** At least thirty days written notice before any change. If a new rate does not work for you, you may end service without penalty."],
    ["p", "**Past due accounts.** An account more than thirty days past due may result in suspension of service after written notice. We will try to reach you and your responsible party before any service is suspended."],
    ["h", "3. Long Term Care Insurance"],
    ["p", "If you hold a long term care policy, we will give your carrier everything it asks for: invoices, visit records, caregiver time verification, and your plan of care. We will help you with the claim."],
    ["p", "What we cannot do is guarantee what the carrier pays. You remain responsible for every invoice. Anything the carrier declines, delays, or pays below the invoiced amount is still yours to pay."],
  ],
  billOfRights: [
    ["title", "Patient Bill of Rights & Self-Determination"],
    ["p", "These rights belong to you. Nothing in any agreement with Godwins Family Care limits them."],
    ["h", "Your Rights"],
    ['ul', [
      "To be treated with dignity, respect, and consideration, and to have your property treated with respect.",
      "To receive care without discrimination of any kind.",
      "To be free from verbal, physical, sexual, mental, and financial abuse, neglect, and exploitation.",
      "To be told, before care begins, what services will be provided, who will provide them, and what they will cost.",
      "To take part in planning your care, and to be told in advance of any change to your plan of care.",
      "To refuse any service, treatment, or caregiver, and to be told what refusing may mean for your care.",
      "To request a different caregiver at any time, for any reason.",
      "To privacy in your home and confidentiality of your personal and health information.",
      "To voice a complaint or concern without fear of retaliation, discrimination, or loss of service.",
      "To be told the name and qualifications of anyone providing your care.",
      "To have your property and residence respected, and to be free from solicitation for money, gifts, or loans.",
      "To reasonable notice before services are reduced or ended.",
      "To choose any provider you wish. Accepting home care from Godwins Family Care does not require you to use Godwins Family Care for any medical service.",
      "To formulate an advance directive and to have it honored to the extent permitted by law.",
      "To review your service record on request.",
    ]],
    ["h", "Your Responsibilities"],
    ['ul', [
      "To give accurate information about your health, medications, and living situation, and to tell us when things change.",
      "To take part in your plan of care and tell us when something is not working.",
      "To provide a safe home environment for your caregiver, including disclosing hazards, firearms, and animals.",
      "To treat your caregiver with respect and to refrain from asking a caregiver to perform tasks outside the plan of care.",
      "To give at least twenty four hours notice when cancelling or changing a scheduled visit.",
      "To meet the financial obligations set out in your service agreement.",
      "To tell us promptly about any concern with your care.",
    ]],
    ["h", "How to Raise a Concern"],
    ["p", "Call Godwins Family Care at **404-913-6705** or email **admin@godwinsfamilycarellc.com**. We will acknowledge your concern, look into it, and respond. Raising a concern will never affect the care you receive."],
    ["p", "You also have the right to contact the State of Georgia directly at any time, without first contacting us."],
  ],
  npp: [
    ["title", "HIPAA Notice of Privacy Practices"],
    ["p", "This notice describes how information about you may be used and disclosed, and how you can get access to this information. Please review it carefully."],
    ["p", "**This notice covers the home care agency.** It describes the privacy practices of the Godwins Family Care **private home care** agency. If you also receive In-Home Primary Care from our nurse practitioner, that medical practice issues its own separate Notice of Privacy Practices, which you would receive and acknowledge separately."],
    ["h", "Our Commitment"],
    ["p", "Godwins Family Care LLC is required by law to protect the privacy of your health information, to give you this notice describing our legal duties and privacy practices, and to follow the terms of the notice currently in effect."],
    ["h", "How We May Use and Disclose Your Information"],
    ["p", "**For your treatment and care.** We share your information with the caregivers and staff involved in your care, and with your physicians, nurse practitioners, pharmacies, and other providers, so that your care is coordinated and safe."],
    ["p", "**For payment.** We use your information to bill and receive payment, including submitting documentation to your long term care insurance carrier or another payer you have authorized."],
    ["p", "**For our operations.** We use your information to supervise caregivers, review quality of care, train staff, and run the business of the agency."],
    ["p", "**To family and others involved in your care.** Unless you object, we may share information relevant to your care with a family member, representative, or other person you have identified."],
    ["p", "**As required by law.** We may disclose information when required by law, including to health oversight agencies, for public health activities, in response to a court order, and to report suspected abuse, neglect, or exploitation. Georgia law requires our staff to report suspected abuse, neglect, or exploitation of an adult."],
    ["p", "**To prevent a serious threat.** We may disclose information when necessary to prevent a serious threat to your health or safety or to the health or safety of another person."],
    ["p", "**Uses that require your written authorization.** Most uses and disclosures not described above require your written authorization, including any marketing use and any sale of your information. We do not sell your information. You may revoke an authorization at any time in writing, and the revocation applies going forward."],
    ["h", "Your Rights Regarding Your Information"],
    ['ul', [
      "To inspect and receive a copy of your record, in paper or electronic form.",
      "To ask us to correct information you believe is incorrect or incomplete.",
      "To receive a list of certain disclosures we have made of your information.",
      "To request that we limit how we use or share your information. We will consider every request and will accommodate reasonable ones.",
      "To ask that we contact you in a specific way or at a specific address.",
      "To receive a paper copy of this notice at any time, even if you agreed to receive it electronically.",
      "To be notified if a breach occurs that compromises the privacy or security of your information.",
      "To file a complaint if you believe your privacy rights have been violated. You will not be penalized or retaliated against for filing a complaint.",
    ]],
    ["h", "Complaints and Contact"],
    ["p", "To exercise any right above, or to file a complaint, contact the Privacy Officer at Godwins Family Care LLC, 4300 Paces Ferry Rd SE, Suite 500, Atlanta, GA 30339, telephone 404-913-6705, email admin@godwinsfamilycarellc.com."],
    ["p", "You may also file a complaint with the Secretary of the U.S. Department of Health and Human Services, Office for Civil Rights. We will not retaliate against you for filing a complaint."],
    ["p", "We reserve the right to change this notice and to make the revised notice effective for information we already hold as well as information we receive in the future. A current copy will be provided on request."],
  ],
  pcaScope: [
    ["title", "Personal Care Aide Scope Acknowledgment"],
    ["p", "**Consent to personal home care.** I consent to receive **non-medical** personal home care services from Godwins Family Care LLC as described in the Home Care Service Agreement and my plan of care. I understand this is not consent to medical treatment and that no medical service is being provided under this packet. I understand these services are non-medical, that caregivers do not administer medication or perform skilled nursing tasks, and that I may refuse any service at any time."],
    ["p", "**Personal care aide scope.** I understand that a personal care aide provides reminders and support and observes and reports changes in my condition. An aide does not administer medication, perform any skilled nursing task, or make clinical decisions. If I need a service outside this scope, Godwins Family Care will tell me and will help me arrange it with a licensed clinician."],
    ["p", "**Long term care insurance claim assistance.** I authorize Godwins Family Care to communicate with my long term care insurance carrier and to provide the invoices, visit records, caregiver time verification, and plan of care documentation the carrier requires to process my claim. I understand that I remain responsible for payment of all invoices regardless of what the carrier pays."],
    ["p", "**Advance directive.** You have the right to make decisions about your medical care, including the right to accept or refuse treatment and to create an advance directive. Godwins Family Care does not require you to have one. Your advance directive status is recorded once on your Client Information Face Sheet."],
    ["p", "**Emergency information.** Emergency contacts, primary care provider, preferred hospital, pharmacy, and allergies are recorded on your Client Information Face Sheet, which forms part of this consent. Please confirm they are correct rather than writing them again."],
  ],
  roiFamily: [
    ["title", "Release of Information — Family"],
    ["p", "I authorize Godwins Family Care to exchange information about my care with the people and organizations I identify, for the purpose of coordinating my care. This authorization remains in effect until I revoke it in writing."],
    ["p", "**This authorization is what unlocks the family portal.** The people you name here are the people who may see your care information."],
    ["p", "To authorize release of medical records from a specific provider or facility, complete the Release of Information — Providers instead. That is a different form and covers a different thing."],
  ],
  roiProvider: [
    ["title", "Release of Information — Providers"],
    ["p", "This form authorizes one provider or facility to release your records to Godwins Family Care. Complete one for each provider. This authorization is voluntary and is not a condition of receiving care."],
    ["p", "**Why the home care agency asks for records.** Records requested under this form are used to build a safe **home care** plan: to know your diagnoses, allergies, mobility limits, fall risk, and diet so your caregiver supports you correctly. This is not a request for medical treatment and does not enroll you in medical care."],
    ["h", "Release To"],
    ["p", "**Godwins Family Care LLC**, 4300 Paces Ferry Rd SE, Suite 500, Atlanta, GA 30339. Telephone 404-913-6705, fax 678-692-7445."],
    ["h", "Information to Be Released"],
    ["p", "You choose which records to release: history and physical, progress and office notes, discharge summary, medication list, laboratory results, imaging reports, immunization record, consultation reports, therapy notes, functional or ADL assessment, advance directive or POLST, face sheet and demographics, or the entire record."],
    ["h", "Specially Protected Records"],
    ["p", "Some records carry extra federal protection and are released only if you say so specifically: mental or behavioral health, substance use treatment under 42 CFR Part 2, HIV or AIDS related, genetic testing, and sexually transmitted infection records."],
    ["h", "Purpose, Expiration, and Your Rights"],
    ["p", "**Purpose.** To coordinate my home care and plan of care with Godwins Family Care, and to support a long term care insurance claim where applicable."],
    ["p", "**Expiration.** This authorization expires one year from the date signed, unless I write a different date or event."],
    ["p", "**Right to revoke.** I may revoke this authorization at any time by writing to Godwins Family Care at the address above. Revoking it does not undo anything already done in reliance on it."],
    ["p", "**Redisclosure.** Information released under this authorization may no longer be protected by federal privacy law once received, and could be redisclosed by the recipient. Records protected under 42 CFR Part 2 may not be redisclosed without my further written permission."],
    ["p", "**Voluntary.** Signing this form is voluntary. Godwins Family Care will not condition my treatment, payment, enrollment, or eligibility for benefits on whether I sign it."],
    ["p", "**Copy.** I am entitled to a copy of this signed authorization."],
  ],
  emergencyFinancial: [
    ["title", "Emergency Response and Financial Responsibility"],
    ["p", "This document covers two things: what your caregiver does in an emergency, and who pays for what."],
    ["p", "**This is not a consent to medical treatment.** Signing this does not authorize Godwins Family Care to examine, diagnose, or treat you. Our caregivers are **not** clinicians and provide no medical care. This form authorizes one thing only: that in an emergency your caregiver may call 911 and give responders the information they need to help you."],
    ["h", "1. Authorization to Summon Emergency Help"],
    ["p", "If I appear to be experiencing a medical emergency and I am unable to make or communicate a decision, I authorize Godwins Family Care staff to call 911, to allow emergency responders access to my home, and to give responders the health information they need to treat me safely, including my medications, allergies, conditions, and any advance directive on file."],
    ["p", "I understand that Godwins Family Care caregivers are not emergency responders and do not provide medical treatment of any kind. Their role is to summon help, keep me safe until help arrives, and notify my emergency contacts. Any treatment I receive is provided by the emergency responders, the hospital, or my own medical providers, and my consent to that treatment is given to them, not to Godwins Family Care."],
    ["h", "2. Advance Directive and Resuscitation Status"],
    ["p", "Godwins Family Care caregivers follow emergency responder direction. A do-not-resuscitate order is honored by emergency responders only where a valid Georgia order is present in the home and produced at the time. Your resuscitation status and any directive on file are recorded on your Client Information Face Sheet."],
    ["h", "3. Financial Responsibility for Emergency Care"],
    ["p", "I understand that ambulance transport, emergency department care, hospital care, and any treatment provided by emergency responders or a hospital are billed by those providers, not by Godwins Family Care, and that I or my insurance am responsible for those charges. Godwins Family Care does not bill for, collect for, or control the cost of emergency services."],
    ["h", "4. Financial Responsibility for Home Care Services"],
    ["p", "I am responsible for payment of all Godwins Family Care invoices at the rates set out in the Home Care Service Agreement. Where a long term care insurance carrier or other payer is involved, I understand that Godwins Family Care will assist with the claim but that the carrier's decision is between the carrier and me. Amounts a carrier declines, delays, or pays below the invoiced total remain my responsibility."],
    ["h", "5. Responsible Party Guarantee, If Applicable"],
    ["p", "Where someone other than the client accepts financial responsibility, that responsible party agrees to pay Godwins Family Care invoices that the client does not pay when due."],
  ],
  crisisProtocol: [
    ["title", "Emergency & Crisis Protocol (911/988)"],
    ["p", "What your caregiver will do, and who they will call. Keep this where you can find it."],
    ["h", "1. Medical Emergency"],
    ["p", "Signs include chest pain, difficulty breathing, sudden weakness or trouble speaking, a fall with injury or a head strike, uncontrolled bleeding, seizure, or loss of consciousness."],
    ['ul', [
      "The caregiver calls **911** first and stays with the client.",
      "The caregiver calls Godwins Family Care at **404-913-6705**.",
      "Godwins Family Care notifies the emergency contact and, where authorized, the client's medical providers.",
      "The caregiver does not move a client after a fall with suspected injury and does not administer medication.",
    ]],
    ["h", "2. Urgent but Not an Emergency"],
    ["p", "A change in condition that needs attention today but is not life threatening: new confusion, fever, refusal to eat or drink, a fall without apparent injury, a medication the client cannot locate, or a sudden change in mood or behavior."],
    ['ul', [
      "The caregiver calls Godwins Family Care at **404-913-6705** the same day.",
      "Godwins Family Care contacts the client's primary care provider and the emergency contact.",
    ]],
    ["h", "3. Mental Health or Emotional Crisis"],
    ["p", "Thoughts of self-harm, severe distress, or a crisis affecting the client's safety. The caregiver stays with the client where it is safe to do so, calls 988 or 911 as the situation requires, and notifies Godwins Family Care."],
    ["h", "4. Fire, Weather, Power Loss, or Evacuation"],
    ['ul', [
      "The caregiver gets the client to safety first, then calls 911 if needed.",
      "The caregiver calls Godwins Family Care so the family can be notified and coverage arranged.",
      "The client is asked to keep a two-day supply of essential medication and a working flashlight in a known place.",
    ]],
    ["h", "5. No Answer at the Door"],
    ["p", "If the caregiver arrives and cannot reach the client, the caregiver calls the client, then the emergency contact, then Godwins Family Care. Where there is reason to believe the client is inside and in distress, the caregiver calls 911 for a welfare check."],
    ["h", "6. Who We Call, and In What Order"],
    ["p", "The call order, preferred hospital, primary care provider, entry instructions for responders, and pets in the home are recorded on your Client Information Face Sheet. Your caregiver carries that order. Please confirm it is correct today, and tell us whenever it changes."],
  ],
  consentToTreat: [
    ["title", "Consent to Medical Treatment"],
    ["p", "You may refuse any part of this and still receive care."],
    ["h", "A. Consent to Evaluation and Treatment"],
    ["p", "I consent to medical evaluation and treatment by the Godwins Family Care nurse practitioner and collaborating physician, in my home. I understand this includes taking my history, physical examination, vital signs, and developing and carrying out a plan of care with me."],
    ["h", "B. Procedures and Testing"],
    ["p", "I consent to routine services performed in the home as part of my care: drawing blood and collecting specimens, point of care testing such as blood sugar or urine testing, electrocardiogram, wound assessment and dressing, vaccinations and injections that are ordered for me, and ordering laboratory work and imaging performed elsewhere."],
    ["p", "Anything beyond routine will be explained to me first, including why it is recommended, what it involves, the risks, and what happens if I decline."],
    ["h", "C. Prescribing and Medication Management"],
    ["p", "I consent to the nurse practitioner prescribing, adjusting, and discontinuing my medications, reviewing everything I take, and communicating with my pharmacy and my other prescribers. I agree to tell the practice about every medication and supplement I take, including anything prescribed by another provider."],
    ["h", "D. Telehealth — optional"],
    ["p", "I consent to some visits being conducted by video or telephone where clinically appropriate. I understand a telehealth visit has limits, that the provider may require an in-person visit instead, and that I may ask for an in-person visit at any time. You may decline telehealth and receive in-person visits only."],
    ["h", "E. Students and Trainees — optional"],
    ["p", "Optional and entirely voluntary. Declining has no effect on your care. Godwins Family Care hosts nursing and medical students under direct supervision. I consent to a supervised student being present and taking part in my care."],
    ["h", "F. What I Understand"],
    ['ul', [
      "No one has guaranteed me any particular result. Medicine involves judgment, and outcomes cannot be promised.",
      "I may refuse any examination, test, treatment, or medication, at any time, and I will be told what refusing may mean for my health.",
      "I may ask for a second opinion or transfer my care to another provider at any time.",
      "This consent stays in effect for my ongoing care until I revoke it in writing.",
      "This is not emergency care. In an emergency I call 911.",
    ]],
  ],
  assignmentOfBenefits: [
    ["title", "Assignment of Benefits and Financial Responsibility"],
    ["p", "This lets Godwins Family Care bill Medicare or your health plan directly, and sets out what you owe."],
    ["h", "1. Assignment of Benefits"],
    ["p", "I assign to Godwins Family Care LLC all benefits payable to me under Medicare and any other health plan for services the practice provides, and I direct that payment be made directly to Godwins Family Care rather than to me. This assignment applies to current and future claims until I revoke it in writing."],
    ["h", "2. Authorization to Release Information for Claims"],
    ["p", "I authorize Godwins Family Care to release the medical information necessary to determine benefits and process claims to the Centers for Medicare and Medicaid Services, my health plan, and their agents. This includes the diagnosis and service records a claim requires."],
    ["h", "3. What You Owe"],
    ["p", "Assigning your benefits does not mean nothing is owed. You remain responsible for:"],
    ['ul', [
      "Any deductible you have not yet met for the year.",
      "Your coinsurance or copay, which for Medicare Part B is typically twenty percent of the approved amount unless a supplemental plan covers it.",
      "Services your plan does not cover, but only where you were told in advance and in writing and chose to proceed.",
      "Charges your plan denies because coverage lapsed, information was not provided, or the plan's requirements were not met.",
    ]],
    ["p", "Statements are sent after your plan processes the claim. Balances are due within thirty days of the statement date. If a balance is difficult, call the office before it goes past due and a payment arrangement can usually be made."],
    ["h", "4. Advance Notice of Non-Covered Services"],
    ["p", "If the practice believes Medicare will not pay for something recommended, you will be given a written notice before it is provided, explaining what it is, why it may not be covered, and the estimated cost. You then decide whether to proceed. You are never held responsible for a non-covered service you were not warned about in advance."],
    ["h", "5. Responsible Party, If Applicable"],
    ["p", "Where someone other than the patient accepts financial responsibility for balances after insurance, that person is recorded on your Client Information Face Sheet."],
  ],
  practiceNpp: [
    ["title", "Medical Practice Notice of Privacy Practices"],
    ["p", "This notice describes how medical information about you may be used and disclosed by the In-Home Primary Care practice, and how you can get access to it. Please review it carefully."],
    ["p", "**Why you are receiving a second privacy notice.** You already received a Notice of Privacy Practices from the Godwins Family Care **home care agency**. This one is different. It covers the **medical practice**, which keeps a clinical record, bills health plans, and exchanges information with other treating providers. Both notices apply to you, each to its own service."],
    ["h", "Our Commitment"],
    ["p", "The practice is required by law to protect the privacy of your protected health information, to give you this notice of our legal duties and privacy practices, and to follow the terms of the notice currently in effect."],
    ["h", "How We Use and Disclose Your Information"],
    ["p", "**Treatment.** We share your information with the clinicians involved in your care and with specialists, hospitals, laboratories, imaging centers, pharmacies, home health agencies, and other providers treating you, so that your care is coordinated and safe. This includes sharing with the Godwins Family Care home care agency where it affects your safety at home."],
    ["p", "**Payment.** We use and disclose your information to bill and receive payment from Medicare, your health plan, and any secondary payer, including submitting diagnoses, service records, and documentation supporting a claim."],
    ["p", "**Health care operations.** We use your information to review quality of care, evaluate clinician performance, train students and staff, conduct audits, and run the practice."],
    ["p", "**Appointment reminders and health information.** We may contact you to remind you of a visit, to follow up on a result, or to tell you about a treatment alternative or health service that may benefit you."],
    ["p", "**Family and others involved in your care.** Unless you object, we may share information relevant to your care with a family member, representative, or other person you have identified, and with anyone you have authorized on a release of information."],
    ["p", "**As required by law.** We disclose information when the law requires it, including to public health authorities, health oversight agencies, in response to a court order or subpoena, for reporting suspected abuse, neglect, or exploitation of an adult as Georgia law requires, and to report certain communicable diseases and vital events."],
    ["p", "**To prevent a serious threat.** We may disclose information when necessary to prevent a serious threat to your health or safety or that of another person."],
    ["p", "**Uses requiring your written authorization.** Psychotherapy notes, any marketing use, and any sale of your information require your written authorization. We do not sell your information. You may revoke an authorization in writing at any time, effective going forward."],
    ["h", "Your Rights"],
    ['ul', [
      "To inspect and receive a copy of your medical record, in paper or electronic form.",
      "To ask us to amend information you believe is incorrect or incomplete.",
      "To receive an accounting of certain disclosures we have made.",
      "To request a restriction on how we use or share your information. We must honor a request to withhold information from your health plan about a service you paid for in full yourself.",
      "To ask that we contact you in a specific way or at a specific address.",
      "To receive a paper copy of this notice at any time.",
      "To be notified if a breach compromises the privacy or security of your information.",
      "To file a complaint without any penalty or retaliation.",
    ]],
    ["h", "Complaints and Contact"],
    ["p", "To exercise any right above, or to file a complaint, contact the Privacy Officer at Godwins Family Care LLC, 4300 Paces Ferry Rd SE, Suite 500, Atlanta, GA 30339, telephone 404-913-6705, email admin@godwinsfamilycarellc.com."],
    ["p", "You may also file a complaint with the Secretary of the U.S. Department of Health and Human Services, Office for Civil Rights. We will not retaliate against you for filing a complaint."],
    ["p", "We reserve the right to change this notice and to make the revised notice effective for information we already hold as well as information we receive in the future. A current copy will be provided on request."],
  ],
  monitoring: [
    ["title", "Continuous Monitoring Opt-In"],
    ["p", "Optional. In a future release, Godwins Family Care may offer consent-gated in-home remote monitoring (activity and, where shared, video) viewable by your care team and, where you allow it, your family. This option is **inactive** today, and cannot be signed. Nothing is being recorded and nothing starts by leaving this here."],
  ],
};

// Plain text for a consent, for a PDF or any non-HTML renderer.
const consentPlainText = (key) => (CONSENT_TEXT[key] || []).map(([t, v]) =>
  t === 'ul' ? v.map(x => '  \u2022 ' + x.replace(/\*\*/g, '')).join('\n') : String(v).replace(/\*\*/g, ''));

module.exports = { CONSENT_TEXT, consentPlainText };
