#!/usr/bin/env node
// Writes docs/OPENEMR_COVERAGE.md from the one declared catalog.
//
// The document is GENERATED, never hand-edited: a hand-maintained list of what
// works is a list that goes stale silently, which is the exact failure the
// catalog exists to stop. Edit openemrCoverage.js and re-run this.
//
//   node scripts/openemr_coverage.js          writes the file
//   node scripts/openemr_coverage.js --check  exits non-zero if it is stale
const fs = require('fs');
const path = require('path');
const coverage = require('../openemrCoverage');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'docs', 'OPENEMR_COVERAGE.md');

const HEADINGS = {
  live: ['Proven against the live instance',
    'Exercised against the running EMR with the **stored value read back** — not a status code. This repo has been burned six times by a 200 that wrote nothing, so a row is only here when somebody read the data back out.'],
  wired_unproven: ['Wired, not proven',
    'The code exists and is called. **Nobody has run it against a real EMR.** It may 403 on the org-level ACL, 404 on a route 8.4 does not serve, or work perfectly — and those are three different problems with three different fixes. Saying so is the point of the row; an empty result is not a diagnosis.'],
  not_wired: ['Deliberately not wired',
    'A gap somebody **chose**, with the reason. That is a different fact from a gap nobody noticed, and only one of them is a bug.']
};

const table = (rows) => [
  '| Resource | Kind | Since | What to know |',
  '|---|---|---|---|',
  ...rows.map(r => `| \`${r.resource}\` | ${r.kind} | ${r.since} | ${r.note.replace(/\|/g, '\\|')} |`)
].join('\n');

const render = () => {
  const parts = [
    '# OpenEMR coverage',
    '',
    '_Generated by `node scripts/openemr_coverage.js` from `openemrCoverage.js`. **Do not hand-edit** — a hand-maintained list of what works is a list that goes stale silently._',
    '',
    'What this app does with OpenEMR, in three lists, because "written" and "proven" are different facts and the gap between them is where five sessions have lost time.',
    ''
  ];
  for (const status of coverage.STATUSES) {
    const rows = coverage.byStatus(status);
    const [title, blurb] = HEADINGS[status];
    parts.push(`## ${title} (${rows.length})`, '', blurb, '', rows.length ? table(rows) : '_None._', '');
  }
  parts.push(
    '## How a row moves',
    '',
    'From **wired, not proven** to **proven** by running it against the live instance and reading the stored value back, then editing `openemrCoverage.js` and re-running this script. Never by reading the code and deciding it looks right.',
    ''
  );
  return parts.join('\n');
};

const problems = [];
const bad = coverage.malformed();
if (bad.length) problems.push(`rows with no status, kind or note: ${bad.join(', ')}`);
const missing = coverage.untriaged(fs.readFileSync(path.join(ROOT, 'openemr.js'), 'utf8'));
if (missing.length) problems.push(`FHIR resources the transport calls with no row in the catalog: ${missing.join(', ')}`);
if (problems.length) {
  console.error('An untriaged capability is the one most likely to be broken, because nobody has looked at it.');
  for (const p of problems) console.error(`  - ${p}`);
  process.exit(1);
}

const next = render();
if (process.argv.includes('--check')) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (current !== next) {
    console.error(`${path.relative(ROOT, OUT)} is stale — run: node scripts/openemr_coverage.js`);
    process.exit(1);
  }
  console.log(`${path.relative(ROOT, OUT)} is current (${coverage.CATALOG.length} capabilities).`);
} else {
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, next);
  const counts = coverage.STATUSES.map(s => `${coverage.byStatus(s).length} ${s}`).join(' · ');
  console.log(`Wrote ${path.relative(ROOT, OUT)} — ${counts}.`);
}
